/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Minutes = number;
export type Sentences = string;
export type Sentences1 = string;
export type Minutes1 = number;
export type Minutes2 = number;
export type Minutes3 = number;

export interface Recipe {
  name: string;
  description?: string;
  image?: string;
  wait_time?: Minutes | Time;
  meals: ["snack" | "breakfast" | "lunch" | "dinner", ...("snack" | "breakfast" | "lunch" | "dinner")[]];
  servings?: number;
  steps: [Sentences | Step, ...(Sentences | Step)[]];
}
export interface Time {
  amount: number;
  unit?: string;
}
export interface Step {
  text: Sentences1;
  optional?: boolean;
  time?: Minutes1 | Time1 | TimeRange;
  ingredients?: (string | Ingredient)[];
}
export interface Time1 {
  amount: number;
  unit?: string;
}
export interface TimeRange {
  min: Minutes2 | Time2;
  max: Minutes3 | Time3;
}
export interface Time2 {
  amount: number;
  unit?: string;
}
export interface Time3 {
  amount: number;
  unit?: string;
}
export interface Ingredient {
  amount?: number;
  unit?: string | SingularPluralUnit;
  name: string | SingularPluralName;
  note?: string;
}
export interface SingularPluralUnit {
  singular: string;
  plural: string;
}
export interface SingularPluralName {
  singular: string;
  plural: string;
}
