# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
$id: "https://raw.githubusercontent.com/mtoohey31/yams/master/schema.yaml"
title: recipe
type: object
additionalProperties: false
required:
  - name
  - steps
properties:
  name:
    type: string
  wait_time:
    type: number
    exclusiveMinimum: 0
  steps:
    type: array
    items:
      oneOf:
        - type: string
        - type: object
          title: step
          additionalProperties: false
          required:
            - text
          properties:
            text:
              type: string
            optional:
              type: boolean
            ingredients:
              type: array
              items:
                oneOf:
                  - type: string
                  - type: object
                    title: ingredient
                    additionalProperties: false
                    required:
                      - name
                    properties:
                      count:
                        type: number
                        exclusiveMinimum: 0
                      unit:
                        type: string
                      name:
                        type: string
