# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
$id: "https://raw.githubusercontent.com/mtoohey31/yams/master/schema.yaml"
title: recipe
type: object
additionalProperties: false
required:
  - name
  - steps
properties:
  name:
    type: string
  wait_time:
    type: number
    exclusiveMinimum: 0
  steps:
    type: array
    items:
      oneOf:
        - type: string
          title: sentences
          pattern: "[^]*[.!?]"
        - type: object
          title: step
          additionalProperties: false
          required:
            - text
          properties:
            text:
              type: string
              title: sentences
              pattern: "[^]*[.!?]"
            optional:
              type: boolean
            time:
              oneOf:
                - type: number
                  title: minutes
                  exclusiveMinimum: 0
                - type: object
                  title: time
                  additionalProperties: false
                  required:
                    - amount
                  properties:
                    amount:
                      type: number
                      exclusiveMinimum: 0
                    unit:
                      type: string
                - type: object
                  title: time range
                  additionalProperties: false
                  required:
                    - min
                    - max
                  properties:
                    min:
                      oneOf:
                        - type: number
                          title: minutes
                          exclusiveMinimum: 0
                        - type: object
                          title: time
                          additionalProperties: false
                          required:
                            - amount
                          properties:
                            amount:
                              type: number
                              exclusiveMinimum: 0
                            unit:
                              type: string
                    max:
                      oneOf:
                        - type: number
                          title: minutes
                          exclusiveMinimum: 0
                        - type: object
                          title: time
                          additionalProperties: false
                          required:
                            - amount
                          properties:
                            amount:
                              type: number
                              exclusiveMinimum: 0
                            unit:
                              type: string
            ingredients:
              type: array
              items:
                oneOf:
                  - type: string
                  - type: object
                    title: ingredient
                    additionalProperties: false
                    required:
                      - name
                    properties:
                      count:
                        type: number
                        exclusiveMinimum: 0
                      unit:
                        oneOf:
                        - type: string
                        - type: object
                          title: singular/plural unit
                          additionalProperties: false
                          required:
                            - singular
                            - plural
                          properties:
                            singular:
                              type: string
                            plural:
                              type: string
                      name:
                        oneOf:
                        - type: string
                        - type: object
                          title: singular/plural name
                          additionalProperties: false
                          required:
                            - singular
                            - plural
                          properties:
                            singular:
                              type: string
                            plural:
                              type: string
