# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
# TODO: support different methods for a given step, or the whole process
# TODO: use some string templating system to place ingredients and timing into step text
# TODO: split things into separate objects so that things like times can be
# re-used instead of having to copy-paste them
$id: "https://raw.githubusercontent.com/mtoohey31/yams/master/schema.yaml"
title: recipe
type: object
additionalProperties: false
required:
  - name
  - meals
  - steps
properties:
  name:
    type: string
  source:
    type: string
  description:
    type: string
  image:
    type: string
  wait_time:
    oneOf:
      - type: number
        title: minutes
        exclusiveMinimum: 0
      - type: object
        title: time
        additionalProperties: false
        required:
          - amount
        properties:
          amount:
            type: number
            exclusiveMinimum: 0
          unit:
            type: string
  meals:
    type: array
    minItems: 1
    items:
      type: string
      enum:
        - snack
        - breakfast
        - lunch
        - dinner
  servings:
    type: integer
    minimum: 1
  steps:
    type: array
    minItems: 1
    items:
      oneOf:
        - type: string
          title: sentences
          pattern: "[^]*[.!?\\)]$"
        - type: object
          title: step
          additionalProperties: false
          required:
            - text
          properties:
            text:
              type: string
              title: sentences
              pattern: "[^]*[.!?\\)]$"
            optional:
              type: boolean
            time:
              oneOf:
                - type: number
                  title: minutes
                  exclusiveMinimum: 0
                - type: object
                  title: time
                  additionalProperties: false
                  required:
                    - amount
                  properties:
                    amount:
                      type: number
                      exclusiveMinimum: 0
                    unit:
                      type: string
                - type: object
                  title: time range
                  additionalProperties: false
                  required:
                    - min
                    - max
                  properties:
                    min:
                      oneOf:
                        - type: number
                          title: minutes
                          exclusiveMinimum: 0
                        - type: object
                          title: time
                          additionalProperties: false
                          required:
                            - amount
                          properties:
                            amount:
                              type: number
                              exclusiveMinimum: 0
                            unit:
                              type: string
                    max:
                      oneOf:
                        - type: number
                          title: minutes
                          exclusiveMinimum: 0
                        - type: object
                          title: time
                          additionalProperties: false
                          required:
                            - amount
                          properties:
                            amount:
                              type: number
                              exclusiveMinimum: 0
                            unit:
                              type: string
            ingredients:
              type: array
              items:
                oneOf:
                  - type: string
                  - type: object
                    title: ingredient
                    additionalProperties: false
                    required:
                      - name
                    properties:
                      amount:
                        type: number
                        exclusiveMinimum: 0
                      unit:
                        oneOf:
                        - type: string
                        - type: object
                          title: singular/plural unit
                          additionalProperties: false
                          required:
                            - singular
                            - plural
                          properties:
                            singular:
                              type: string
                            plural:
                              type: string
                      name:
                        oneOf:
                        - type: string
                        - type: object
                          title: singular/plural name
                          additionalProperties: false
                          required:
                            - singular
                            - plural
                          properties:
                            singular:
                              type: string
                            plural:
                              type: string
                      note:
                        type: string
